# Generated by Django 4.2.3 on 2023-08-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
    ]
