# Generated by Django 4.2.2 on 2023-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price per night'),
        ),
    ]
