# Generated by Django 4.2.2 on 2023-07-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='user',
        ),
    ]
