# Generated by Django 4.2.3 on 2023-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price per night in $:'),
        ),
    ]
