# Generated by Django 4.2.3 on 2023-07-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_image_alter_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
