# Generated by Django 4.2.3 on 2023-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_remove_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='hotel',
            field=models.CharField(blank=True, null=True),
        ),
    ]
