# Generated by Django 4.2.3 on 2023-07-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_destination_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='hotel',
        ),
    ]
