# Generated by Django 4.2.3 on 2023-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploredestination',
            name='image',
            field=models.ImageField(default=1, upload_to='explore/'),
            preserve_default=False,
        ),
    ]
