# Generated by Django 4.2.3 on 2023-07-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_exploredestination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(default=1, upload_to='attraction_images/'),
            preserve_default=False,
        ),
    ]
