# Generated by Django 4.2.2 on 2023-07-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='user',
            new_name='username',
        ),
    ]
