# Generated by Django 4.2.2 on 2023-07-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profilemodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='gender',
        ),
    ]
