# Generated by Django 4.2.2 on 2023-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profilemodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True),
        ),
    ]
